/**
 * @file pptxExporter.ts
 * @system AMEVA OS Desktop Workstation
 * @location src/main/exporters/pptxExporter.ts
 * @role Core module helper and integration logic
 * 
 * [소비처 - CONSUMERS / USAGE CONTEXT]
 * - 소비처 A (src/main/index.ts): 일렉트론 메인 라이프사이클(ready/will-quit) 및 윈도우 생성 시점에 결합 구동.
 * - 소비처 B (src/main/preload.ts): contextBridge 안전 통로 노출을 위한 핵심 백엔드 기능 공급자로 소비.
 * 
 * [책임 범위 - RESPONSIBILITY]
 * - 본 파일은 AMEVA 시스템 내에서 도메인 목적에 부합하는 연산 및 데이터 처리 흐름을 안전하게 캡슐화한다.
 * - 외부 라이브러리 및 하위 종속성을 조율하고 결과 규격을 일관되게 제공한다.
 * 
 * [절대 깨면 안 되는 계약 - CONTRACT]
 * - MUST: 모든 예외 발생 시 에러를 침묵시키지 말고 에러 로그를 명확하게 남길 것.
 * - MUST NOT: TypeScript any 형식을 우회 수단으로 함부로 선언하지 말 것.
 */

import { createRequire } from 'module'
const require = createRequire(import.meta.url)

const pptxgen = require('pptxgenjs')
import { getPlainTextFromNormalized, inlineToText, type ExporterBlock, type ExporterInlineContent, type ExporterTableRow } from './exportersHelper.js'

export async function exportToPPTX(blocks: ExporterBlock[]): Promise<Buffer> {
  const pptx = new pptxgen()
  pptx.layout = 'LAYOUT_16x9'
  pptx.author = 'AMEVA'

  interface SlideContent {
    type: 'bullet' | 'image' | 'table' | 'code'
    text?: string
    url?: string
    tableRows?: ExporterTableRow[]
  }

  interface SlideData {
    title: string
    contents: SlideContent[]
  }

  const slides: SlideData[] = []
  let currentSlide: SlideData = { title: 'Presentation', contents: [] }

  const processBlock = (block: ExporterBlock) => {
    const text = getPlainTextFromNormalized(block)

    if (block.type === 'heading') {
      const level = Number(block.props?.level) || 1
      if (level === 1) {
        if (currentSlide.contents.length > 0 || currentSlide.title !== 'Presentation') {
          slides.push(currentSlide)
        }
        currentSlide = { title: text, contents: [] }
      } else {
        currentSlide.contents.push({ type: 'bullet', text: `[${level}단계] ${text}` })
      }
    } else if (['bulletListItem', 'numberedListItem', 'paragraph'].includes(block.type)) {
      if (text.trim()) {
        currentSlide.contents.push({ type: 'bullet', text: (block.type === 'numberedListItem' ? '1. ' : '') + text })
      }
    } else if (block.type === 'codeBlock') {
      currentSlide.contents.push({ type: 'code', text })
    } else if (block.type === 'image' && block.props?.url) {
      currentSlide.contents.push({ type: 'image', url: block.props.url })
    } else if (block.type === 'table') {
      const rows = block.tableRows ?? []
      if (rows.length > 0) {
        currentSlide.contents.push({ type: 'table', tableRows: rows })
      }
    }

    if (Array.isArray(block.children)) {
      block.children.forEach(processBlock)
    }
  }

  blocks.forEach(processBlock)
  if (currentSlide.contents.length > 0 || currentSlide.title !== 'Presentation') {
    slides.push(currentSlide)
  }

  if (slides.length === 0) {
    slides.push({ title: 'AMEVA Document Summary', contents: [{ type: 'bullet', text: '문서 내용이 비어 있습니다.' }] })
  }

  const coverSlide = pptx.addSlide()
  coverSlide.background = { fill: '0B0F19' }
  coverSlide.addShape(pptx.shapes.RECTANGLE, { x: 0.8, y: 3.4, w: 11.7, h: 0.04, fill: { type: 'solid', color: '8B5CF6' }, line: { color: 'transparent' } })
  coverSlide.addText('AMEVA WORKSTATION PRESENTATION', { x: 0.8, y: 2.8, w: 11.7, h: 0.4, fontSize: 13, bold: true, color: '8B5CF6', fontFace: 'Calibri', charSpacing: 6 })
  coverSlide.addText(slides[0]?.title || 'Document Report', { x: 0.8, y: 3.8, w: 11.7, h: 1.8, fontSize: 44, bold: true, color: 'FFFFFF', fontFace: 'Calibri' })
  coverSlide.addText(new Date().toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric' }) + ' · Generated by AMEVA', { x: 0.8, y: 6.2, w: 8, h: 0.4, fontSize: 11, color: '6B7280', fontFace: 'Calibri' })

  slides.forEach((slideData, idx) => {
    const MAX_BULLETS_PER_PAGE = 6
    const bulletItems = slideData.contents.filter(c => c.type === 'bullet')
    const images = slideData.contents.filter(c => c.type === 'image')
    const tables = slideData.contents.filter(c => c.type === 'table')
    const codes = slideData.contents.filter(c => c.type === 'code')

    if (codes.length > 0 && bulletItems.length === 0 && tables.length === 0) {
      codes.forEach((codeItem, cIdx) => {
        const slide = pptx.addSlide()
        slide.background = { fill: '0F172A' }
        slide.addText(`${slideData.title} - Source Code ${codes.length > 1 ? `(${cIdx + 1})` : ''}`, { x: 0.6, y: 0.4, w: 12.0, h: 0.8, fontSize: 26, bold: true, color: '8B5CF6', fontFace: 'Calibri' })
        slide.addText(codeItem.text || '', {
          x: 0.6, y: 1.4, w: 12.0, h: 5.2,
          fontSize: 12,
          color: '38BDF8',
          fontFace: 'Courier New',
          fill: { color: '030712' },
          line: { color: '334155', width: 1.5 },
          valign: 'top',
          margin: [15, 15, 15, 15]
        })
      })
      return
    }

    if (tables.length > 0) {
      tables.forEach((tableItem, tIdx) => {
        const slide = pptx.addSlide()
        slide.background = { fill: '0A0A14' }
        slide.addText(`${slideData.title} - Table ${tables.length > 1 ? `(${tIdx + 1})` : ''}`, { x: 0.6, y: 0.4, w: 12.0, h: 0.8, fontSize: 26, bold: true, color: 'FFFFFF', fontFace: 'Calibri' })
        
        if (bulletItems.length > 0) {
          const leadText = bulletItems.slice(0, 2).map(b => b.text).join('\n')
          slide.addText(leadText, { x: 0.6, y: 1.2, w: 12.0, h: 0.8, fontSize: 13, color: '9CA3AF', fontFace: 'Calibri' })
        }

        const rawRows = tableItem.tableRows || []
        const formattedTableData = rawRows.map((rowObj: ExporterTableRow, ri: number) => {
          const cells = (Array.isArray(rowObj.cells) ? rowObj.cells : []) as (ExporterInlineContent[] | unknown)[]
          return cells.map((cell: ExporterInlineContent[] | unknown) => {
            const txt = Array.isArray(cell) ? inlineToText(cell as ExporterInlineContent[]) : ''
            return {
              text: txt,
              options: {
                fill: ri === 0 ? '1F2937' : '111827',
                color: ri === 0 ? '8B5CF6' : 'D1D5DB',
                bold: ri === 0,
                align: 'center',
                fontFace: 'Calibri',
                fontSize: 11,
                border: { pt: 1, color: '374151' }
              }
            }
          })
        })

        if (formattedTableData.length > 0) {
          slide.addTable(formattedTableData, {
            x: 0.6,
            y: bulletItems.length > 0 ? 2.1 : 1.4,
            w: 12.0,
            h: bulletItems.length > 0 ? 4.5 : 5.2
          })
        }
      })
      return
    }

    const totalPages = Math.max(1, Math.ceil(bulletItems.length / MAX_BULLETS_PER_PAGE))
    
    for (let pageIdx = 0; pageIdx < totalPages; pageIdx++) {
      const slide = pptx.addSlide()
      slide.background = { fill: '0A0A14' }
      slide.addShape(pptx.shapes.RECTANGLE, { x: 0, y: 0, w: 0.05, h: 7.5, fill: { type: 'solid', color: idx % 2 === 0 ? '8B5CF6' : '06B6D4' }, line: { color: 'transparent' } })

      const pageSuffix = totalPages > 1 ? ` (${pageIdx + 1}/${totalPages})` : ''
      slide.addText(slideData.title + pageSuffix, { x: 0.6, y: 0.4, w: 12.0, h: 0.8, fontSize: 28, bold: true, color: 'FFFFFF', fontFace: 'Calibri' })
      slide.addShape(pptx.shapes.RECTANGLE, { x: 0.6, y: 1.25, w: 12.0, h: 0.01, fill: { type: 'solid', color: '374151' }, line: { color: 'transparent' } })

      const startIdx = pageIdx * MAX_BULLETS_PER_PAGE
      const endIdx = startIdx + MAX_BULLETS_PER_PAGE
      const pageBullets = bulletItems.slice(startIdx, endIdx)

      const hasImage = images.length > 0 && pageIdx === 0
      const textWidth = hasImage ? 7.0 : 12.0
      
      if (pageBullets.length > 0) {
        const textRuns = pageBullets.map(b => ({
          text: `\n${b.text}`,
          options: { fontSize: 16, color: 'D1D5DB', fontFace: 'Calibri', paraSpaceAfter: 12 }
        }))
        slide.addText(textRuns, { x: 0.6, y: 1.5, w: textWidth, h: 5.0, valign: 'top' })
      }

      if (hasImage && images[0].url) {
        try {
          slide.addImage({
            path: images[0].url,
            x: 7.9,
            y: 1.5,
            w: 4.8,
            h: 4.8,
            sizing: { type: 'contain', w: 4.8, h: 4.8 }
          })
        } catch (imgErr) {
          console.warn('[exportToPPTX] 이미지 삽입 실패:', imgErr)
        }
      }

      slide.addText(`${pageIdx + 1} / ${totalPages}`, { x: 11.5, y: 7.0, w: 1.2, h: 0.3, fontSize: 9, color: '4B5563', fontFace: 'Calibri', align: 'right' })
    }
  })

  const buffer = await pptx.write('arraybuffer')
  return Buffer.from(buffer)
}
